//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_CustDedupeAPIResponse
    {
        public int SrNo { get; set; }
        public string SessionId { get; set; }
        public string RefID { get; set; }
        public string StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public string WalletID { get; set; }
        public string KYCStatus { get; set; }
        public string CustType { get; set; }
        public string CustAddress { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string FIELD1 { get; set; }
        public string FIELD2 { get; set; }
        public string FIELD3 { get; set; }
        public string FIELD4 { get; set; }
        public string FIELD5 { get; set; }
        public string Checksum { get; set; }
    }
}
