//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxisSetuAPILogger
    {
        public int srno { get; set; }
        public string RequestGuid { get; set; }
        public string subheaderMethod { get; set; }
        public string subheader { get; set; }
        public string request { get; set; }
        public string requestEncrypted { get; set; }
        public string responseEncrypted { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> Currenttime { get; set; }
    }
}
