//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_TagIssuance
    {
        public int srno { get; set; }
        public int walletId { get; set; }
        public string subWalletId { get; set; }
        public string operationId { get; set; }
        public string tagdispatch { get; set; }
        public string tagSequenceId { get; set; }
        public string postNumber { get; set; }
        public string productId { get; set; }
        public string paymentType { get; set; }
        public int vehiclevehicleCategory { get; set; }
        public string vehiclevehicleComm { get; set; }
        public string ownermobileNumber { get; set; }
        public string ownerownerName { get; set; }
        public string owneremailId { get; set; }
        public string ownercustAddresscustomerAddres { get; set; }
        public string ownercustAddresscustomerCity { get; set; }
        public string ownercustAddresscustomerState { get; set; }
        public string ownercustAddresspincode { get; set; }
        public string documentdocumentType { get; set; }
        public string documentdocumentNumber { get; set; }
    }
}
