//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_CreateWalletAPI
    {
        public int srno { get; set; }
        public string custemailId { get; set; }
        public string vehmobilenumber { get; set; }
        public string chasisnumber { get; set; }
        public Nullable<decimal> issuanceamt { get; set; }
        public string custfirstname { get; set; }
        public string regstate { get; set; }
        public string paymentstatus { get; set; }
        public string custaddress { get; set; }
        public string rccopynumber { get; set; }
        public string walletId { get; set; }
        public string custpincode { get; set; }
        public string productId { get; set; }
        public string custcity { get; set; }
        public string vehdriveremail { get; set; }
        public Nullable<decimal> depositamt { get; set; }
        public Nullable<decimal> custtype { get; set; }
        public string custlastname { get; set; }
        public string field10 { get; set; }
        public string commercialtype { get; set; }
        public string custdob { get; set; }
        public string vehclass { get; set; }
        public string agentId { get; set; }
        public string posnumber { get; set; }
        public string paymentrefnumber { get; set; }
        public string paymentremarks { get; set; }
        public Nullable<decimal> taxtamt { get; set; }
        public string custstate { get; set; }
        public string vehdrivername { get; set; }
        public string operationId { get; set; }
        public string vehregnumber { get; set; }
        public string regexpiry { get; set; }
        public string channelId { get; set; }
        public string cifId { get; set; }
        public string tagdispatch { get; set; }
        public string accountnumber { get; set; }
        public string enginenumber { get; set; }
        public string custmobilenumber { get; set; }
        public string documenttype { get; set; }
        public string vehweight { get; set; }
        public string sessionId { get; set; }
        public string ifsccode { get; set; }
        public string field1 { get; set; }
        public string cubiccapacity { get; set; }
        public string regdate { get; set; }
        public string field7 { get; set; }
        public string custgender { get; set; }
        public string field6 { get; set; }
        public string documentId { get; set; }
        public string field9 { get; set; }
        public string bankname { get; set; }
        public string field8 { get; set; }
        public string tagseq { get; set; }
        public string field3 { get; set; }
        public string field2 { get; set; }
        public string paymenttype { get; set; }
        public string field5 { get; set; }
        public string field4 { get; set; }
    }
}
