//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_OTPValidationAPI
    {
        public int srno { get; set; }
        public string otp { get; set; }
        public string otpReferenceId { get; set; }
        public Nullable<bool> isOTPValidated { get; set; }
    }
}
