//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_BillDetails
    {
        public int SrNo { get; set; }
        public Nullable<long> BillNo { get; set; }
        public string VehicleType { get; set; }
        public string TagSerialNo { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
