//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusBank_APILogs
    {
        public int srno { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AuthorizationHeader { get; set; }
        public string Body { get; set; }
        public string ResponseBodyEncrypted { get; set; }
        public string ResponseBodyDecrypted { get; set; }
    }
}
