//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusInd_Token_Secrete
    {
        public int srno { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Token { get; set; }
        public string TokenSecrete { get; set; }
    }
}
