//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int SrNo { get; set; }
        public string ReportName { get; set; }
        public string ReportSQL { get; set; }
        public string ReportAccess { get; set; }
        public string ReportActiveStatus { get; set; }
        public Nullable<System.DateTime> ReportCreatedDate { get; set; }
    }
}
