//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TollPlazzPayment
    {
        public int srno { get; set; }
        public string VehicleRegNo { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<System.DateTime> TollEntryTime { get; set; }
        public Nullable<decimal> TollAmtAdded { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string Remark { get; set; }
    }
}
