//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TollVehicleType
    {
        public int srno { get; set; }
        public string VehicleType { get; set; }
        public string VehicleTypeDesc { get; set; }
        public string VehicleTypeStatus { get; set; }
        public string VehicleFASTTagMapperClass { get; set; }
        public Nullable<decimal> AxisThresholdAmount { get; set; }
    }
}
