//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranP_TruckTypes
    {
        public int SrNo { get; set; }
        public string TRUCK_TYPE { get; set; }
        public string SIZE_FT { get; set; }
        public string MAX_WEIGHT { get; set; }
    }
}
