//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTollTracker
    {
        public int srno { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> TollPlazzaNo { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public Nullable<decimal> TollCost { get; set; }
        public Nullable<System.DateTime> tripDate { get; set; }
        public Nullable<System.DateTime> tripEndDate { get; set; }
        public string isVerifiedByToll { get; set; }
        public string isCostDeducted { get; set; }
        public string isSettlementDone { get; set; }
        public string TollRemark { get; set; }
        public Nullable<System.DateTime> Geofence1000 { get; set; }
        public Nullable<System.DateTime> Geofence500 { get; set; }
        public Nullable<System.DateTime> Geofence200 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string isMulti { get; set; }
    }
}
