//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_RechargeResponse
    {
        public int srno { get; set; }
        public string walletId { get; set; }
        public string field1 { get; set; }
        public string etctxnNumber { get; set; }
        public string field3 { get; set; }
        public string field2 { get; set; }
        public string statusMessage { get; set; }
        public string channelId { get; set; }
        public string field5 { get; set; }
        public string uniquerefNumber { get; set; }
        public string statusCode { get; set; }
        public string field4 { get; set; }
    }
}
