//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorCreditAccount
    {
        public int srno { get; set; }
        public Nullable<int> distributorid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string DepositedVia { get; set; }
        public string AcceptedBy { get; set; }
        public string TransactionOTP { get; set; }
    }
}
