//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Tag_Request
    {
        public int SrNo { get; set; }
        public Nullable<int> DistId { get; set; }
        public string TagTypeID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
    }
}
