//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusInd_TagStockDetails
    {
        public int SrNo { get; set; }
        public string Tag_ID { get; set; }
        public string Serial_Number { get; set; }
        public string Batch_Number { get; set; }
        public int Lot_Number { get; set; }
        public string Vehicle_Type { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> SalesPerson_Assign_Date { get; set; }
        public Nullable<int> SalesPerson_Id { get; set; }
        public Nullable<int> Distributor_Id { get; set; }
        public Nullable<System.DateTime> Distributor_Assign_Date { get; set; }
        public string Revert_Status { get; set; }
        public Nullable<System.DateTime> Revert_Date { get; set; }
    }
}
