//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusInd_walletRecharge
    {
        public int SrNo { get; set; }
        public string Transac_IPAddress { get; set; }
        public string TransactionID { get; set; }
        public int PaymentType { get; set; }
        public string TagAccountNo { get; set; }
        public string MobileNumber { get; set; }
        public decimal Amount { get; set; }
        public decimal RechargePercentage { get; set; }
        public decimal TotalAmount { get; set; }
        public string BankStatus { get; set; }
    }
}
