//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagReplacementReq
    {
        public int SrNo { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<System.DateTime> ApprovDate { get; set; }
        public string OldSrNo { get; set; }
        public string NewSrNo { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public string VehicleClass { get; set; }
        public Nullable<int> DistID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> OTP { get; set; }
        public string CustMobNo { get; set; }
        public string BankStatus { get; set; }
    }
}
