//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TollPlazaEmployee
    {
        public int srno { get; set; }
        public Nullable<int> TollPlazzaID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string userEmail { get; set; }
        public string mobno1 { get; set; }
        public string mobno2 { get; set; }
        public string status { get; set; }
        public string userRollstatus { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public Nullable<System.DateTime> isOnlineSince { get; set; }
        public string OTP_ValidTime { get; set; }
    }
}
