//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Vehicle
    {
        public long srno { get; set; }
        public Nullable<int> userid { get; set; }
        public string uservehicleType { get; set; }
        public string uservehicleRegNo { get; set; }
        public string uservehicleStatus { get; set; }
        public string RFIDNumber { get; set; }
        public string BankName { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string isNearByFree { get; set; }
        public string AddressProofDocPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RC_FrontImage { get; set; }
        public string RC_BackImage { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
