//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_RFID
    {
        public int ecom_srno { get; set; }
        public string ecom_RFIDTagSrNo { get; set; }
        public string Serial_Number { get; set; }
        public string Batch_Number { get; set; }
        public string Lot_Number { get; set; }
        public string Vehicle_Type { get; set; }
        public string ecom_axis_WalletID { get; set; }
        public string ecom_CustomerFName { get; set; }
        public string ecom_CustomerLName { get; set; }
        public string ecom_DistributionID { get; set; }
        public string ecom_OTP { get; set; }
        public Nullable<bool> ecom_isAllocated { get; set; }
        public string ecom_RFIDStatus { get; set; }
        public Nullable<int> ecom_CustomerId { get; set; }
        public string ecom_CustomerMobNo { get; set; }
        public string ecom_CustomerVehicleNo { get; set; }
        public string ecom_CustomerVehicleType { get; set; }
        public string ecom_CustomerIdentity { get; set; }
        public Nullable<System.DateTime> ecom_CreatedDate { get; set; }
    }
}
