//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusInd_VehicleClassDetails
    {
        public int VehicleID { get; set; }
        public int VehicleClassId { get; set; }
        public string VehicleType { get; set; }
        public decimal Amount { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal CardCost { get; set; }
    }
}
