//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusInd_CustomerKYC
    {
        public int srno { get; set; }
        public string CustomerMobileNo { get; set; }
        public string CustomerPAN { get; set; }
        public string CustomerPANImage { get; set; }
        public string CustomerAddarNo { get; set; }
        public string CustomerAddhareImage { get; set; }
    }
}
