//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_CustDedupeAPI
    {
        public int srno { get; set; }
        public string agentId { get; set; }
        public string mobilenumber { get; set; }
        public string posnumber { get; set; }
        public string sessionId { get; set; }
        public string field1 { get; set; }
        public string vehregnumber { get; set; }
        public string refId { get; set; }
        public string field3 { get; set; }
        public string field2 { get; set; }
        public string custname { get; set; }
        public string custdob { get; set; }
        public string field5 { get; set; }
        public Nullable<int> channelId { get; set; }
        public string field4 { get; set; }
    }
}
