//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuerFASTag
    {
        public int srno { get; set; }
        public string IssuerBank { get; set; }
        public string CustomerCareHelplineNo { get; set; }
        public string BankUPIHandle { get; set; }
        public string Status { get; set; }
    }
}
