//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapperVehicleClass
    {
        public int SrNo { get; set; }
        public Nullable<int> MapperVehicleClass1 { get; set; }
        public string MapperVehicleDescription { get; set; }
        public Nullable<decimal> AxisThresholdAmount { get; set; }
    }
}
