//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPTPWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int srno { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BusinessName { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string userEmail { get; set; }
        public string mobno1 { get; set; }
        public string mobno2 { get; set; }
        public string status { get; set; }
        public string userRollstatus { get; set; }
        public string deviceId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string profilephoto { get; set; }
        public Nullable<int> TempOTP { get; set; }
    }
}
